### ISSUE TITLE
Add support for managed identity

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#706] opened 2023-08-30 21:57 UTC
#### Is your feature related to a problem? Please describe.

Currently there is no way to configure the transport for managed identity, instead the package assumes a connection string will be used.

#### Describe the requested feature

Provide necessary support to the package to support [managed identity connection configuration for the Azure Service Bus transport](https://docs.particular.net/transports/azure-service-bus/configuration#connectivity-token-credentials), ideally [integrating with existing norms for connection configuration](https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-based-connections-tutorial-2#connect-to-service-bus-in-your-function-app) when using managed identity.
        
#### Describe alternatives you've considered

None

### Additional Context

The missing feature was raised via https://github.com/Particular/NServiceBus.AzureFunctions.Worker.ServiceBus/issues/369

**Comment by andreasohlund** [comment] 2024-05-30 06:34
Closing as a duplicate of https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/390

**Closed by andreasohlund** 2024-05-30 06:34 UTC
Labels: Feature
