### ISSUE TITLE
Not intuitive how to provide managed identity token

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#549] opened 2022-10-17 10:13 UTC
It is not very intuitive on how to provide a managed identity token. The following snippet shows how this can be achieved when using `4.0.0-rc.2`:

```c#
[assembly:NServiceBusTriggerFunction("test")]
public class Program
{
    public static void Main()
    {
        var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .UseNServiceBus(configuration =>
            {
                var endpointConfiguration = configuration.AdvancedConfiguration;
                var transport = endpointConfiguration.UseTransport<AzureServiceBusTransport>();
                transport.ConnectionString("[namespace].servicebus.windows.net");
                transport.CustomTokenCredential(new DefaultAzureCredential());
            })
            .Build();

        host.Run();
    }
}
```

**Comment by ramonsmits** [comment] 2022-10-17 12:00
The following shows how to obtain FQDN from the environment: https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/390

**Comment by shawnz88** [comment] 2022-10-17 13:04
In 4.0.0-rc.2 the minimal working code is:

Program.cs
public static async Task Main()
    {
        var host = new HostBuilder()
            .ConfigureFunctionsWorkerDefaults()
            .UseNServiceBus("endpointname", "[namespace].servicebus.windows.net", configuration =>
            {
                configuration.Transport.TokenCredential = new DefaultAzureCredential();
            })
            .Build();

        await host.RunAsync();
    }

local.settings.json:

"AzureWebJobsServiceBus": "Endpoint=sb://[your_namespace].servicebus.windows.net/;Authentication=ManagedIdentity",
"ServiceBus__fullyQualifiedNamespace": "[your_namespace].servicebus.windows.net",

**Comment by andreasohlund** [comment] 2024-05-30 06:37
Closing as a duplicate of https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/549

**Closed by andreasohlund** 2024-05-30 06:37 UTC
