### ISSUE TITLE
[Question] Get the function ExecutionContext inside an handler

### ISSUE THREAD

**Issue by andrekiba** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#180] opened 2021-04-13 04:46 UTC
Hello and thanks in advance, is there a way to retrieve the function `ExecutionContext` inside an handler?

**Comment by SeanFeldman** [comment] 2021-04-13 05:05
Is there something specific from the `ExecutionContext` you're looking for?

**Comment by SeanFeldman** [comment] 2021-04-13 06:27
@andrekiba, the reason I'm asking is that `ExecutionContext` is not available via DI container by design.

> _The dependency injection container only holds explicitly registered type_s. The only services available as injectable types are what are setup in the `Configure` method. As a result, Functions-specific types like `BindingContext` and `ExecutionContext` aren't available during setup or as injectable types.

**Comment by andrekiba** [comment] 2021-04-13 06:38
@SeanFeldman no problem I saw exactly what you posted.
Was just a question for a test in which I need the `FunctionAppDirectory` prop of the context.
In general, is something that you can someway pass without the DI?
Thanks!

**Comment by SeanFeldman** [comment] 2021-04-19 17:48
@andrekiba, you can get the value into the handler even though it's not registered in the container by the SDK by default.

You can register a singleton with Functions SDK that stores the value you need from the `ExecutionContext` and inject it as any other dependency in the handler. Here's how it could be done:

`Startup` class:

```
public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        var services = builder.Services;
        var path = builder.GetContext().ApplicationRootPath);

        services.AddSingleton(_ => new CustomComponent(path);

        builder.UseNServiceBus(() =>
        {
            // removed for brevity 
        });
    }
}
```

`CustomComponent` definition:

```
public class CustomComponent
{
    readonly string initialValue;

    public CustomComponent(string initialValue)
    {
        this.initialValue = $"ApplicationRootPath: {initialValue}";
    }

    public string GetValue() => initialValue;
}
```

Handler code:

```
public class TestMessageHandler : IHandleMessages<TestMessage>
{
    static readonly ILog Log = LogManager.GetLogger<TestMessageHandler>();
    readonly CustomComponent customComponent;

    public FollowupMessageHandler(CustomComponent customComponent)
    {
        this.customComponent = customComponent;
    }

    public Task Handle(TestMessage message, IMessageHandlerContext context)
    {
        Log.Warn($"Custom component returned: {customComponent.GetValue()}");

        return Task.CompletedTask;
    }
}
```

Once a `TestMessage` is sent, the following will be logged:

```
[datetime] Handling TestMessage in TestMessageHandler.
[datetime] Custom component returned: ApplicationRootPath: C:\test\AzureFunctions.Tester\bin\Debug\netcoreapp3.1
[datetime] Executed 'ASBTriggerQueue' (Succeeded, Id=c80df7d8-61b8-4609-94d8-569a2d0046d5, Duration=9ms)
```

Note: I've used the [sample](https://docs.particular.net/samples/previews/azure-functions/service-bus/) to validate this.

@andrekiba if this gives you what you need, feel free to close the issue.

**Closed** 2021-04-22 06:18 UTC
Labels: Discussion
